build:
  variants:
    - tag: 15.1
      containerfile: Containerfile
      aliases: ["latest"]
      default: true
      args:
        FREEBSD_RELEASE: "15.1"
        PHPVER: "84"
        NO_PKGCLEAN: "1"
      cache_dirs:
        - "pkgcache0:/var/cache/pkg"
        - /home/user/Tests/Ports/files/usr/local/etc/pkg/repos:/usr/local/etc/pkg/repos
        - /usr/local/poudriere/data/packages/150amd64-local:/repo
